#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint

npm run format:check
if [ $? -ne 0 ]; then
  npm run prettier-fix
  npm run format:check
  if [ $? -ne 0 ]; then
    echo "Форматирование не удалось исправить автоматически. Коммит отменён."
    exit 1
  fi
fi
